[project]
name = "ttcli"
version = "3.0.5"
description = "Time tracking tool for the cli"
readme = "README.md"
requires-python = "~=3.13"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.uv.index]]
name = "brbcoffee"
url = "https://pypi.brbcoffee.com/"
publish-url = "https://pypi.brbcoffee.com/"

[tool.poetry]
name = "ttcli"
version = "3.0.5"
description = "Time tracking tool for the cli"
readme = "README.md"
authors = ["Bjørn Snoen <bjorn@snoen.io>"]
include = [{path = "alembic.ini", format = ["sdist", "wheel"]}]
packages = [{include = "ttcli"}]


[tool.poetry.scripts]
tt-cli = "ttcli.main:cli"
tt-a = "ttcli.main:write_to_all_cmd"

[tool.poetry.dependencies]
python = "^3.13"
beautifulsoup4 = "*"
click = "*"
click-help-colors = "*"
html5lib = "*"
python-dateutil = "*"
python-dotenv = "*"
requests = "*"
rich = "*"
pydantic = "^2.6.3"
typing-extensions = "^4.1.1"
inflection = "^0.5.1"
SQLAlchemy = "^1.4.39"
appdirs = "^1.4.4"
alembic = "^1.8.1"
SQLAlchemy-Utils = "^0.38.3"
cryptography = "^37.0.4"
keyring = "^23.7.0"
humps = "^0.2.2"
weasyprint = "^63.0"
jinja2 = "^3.1.2"
babel = "^2.12.1"

[tool.poetry.group.dev.dependencies]
black = "*"
isort = "*"
pytest = "^8.3.4"

[tool.poetry.group.tt-auth.dependencies]
fastapi = {extras = ["all"], version = "^0.110.0"}

[tool.pyright]
include = ["ttcli"]
pythonversion = "3.9"
reportIncompatibleMethodOverride = true
