"""Create config table

Revision ID: 142f6d9e1bc6
Revises: 
Create Date: 2022-08-02 12:58:28.523840

"""
import sqlalchemy as sa
from sqlalchemy_utils.types import StringEncryptedType

from alembic import op

# revision identifiers, used by Alembic.
revision = "142f6d9e1bc6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config",
        sa.Column("service", sa.String(length=50), nullable=False),
        sa.Column("config", StringEncryptedType(), nullable=False),
        sa.PrimaryKeyConstraint("service"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("config")
    # ### end Alembic commands ###
