name: Publish to pypi

on:
  push:
    branches:
      - trunk

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.11
        with:
          poetry_version: "==1.6.1"
          repository_name: brbcoffee
          repository_url: https://pypi.brbcoffee.com/
          repository_username: ${{ secrets.BRBCOFFEE_PYPI_USERNAME }}
          repository_password: ${{ secrets.BRBCOFFEE_PYPI_PASSWORD }}
